- id: lg_tv_on
  alias: LG TV On
  trigger:
  - entity_id: media_player.lg_tv
    from: 'off'
    platform: state
  condition: []
  action:
  - data:
      entity_id: media_player.lg_tv
    service: media_player.volume_up
  - data:
      entity_id: media_player.lg_tv
    service: media_player.volume_up
  - data:
      entity_id: media_player.lg_tv
    service: media_player.volume_up
  - data:
      entity_id: media_player.lg_tv
    service: media_player.volume_up
  - data:
      entity_id: media_player.lg_tv
    service: media_player.volume_up
  - data:
      entity_id: media_player.lg_tv
    service: media_player.volume_up
  - data:
      entity_id: media_player.lg_tv
    service: media_player.volume_up
- id: home_assistant_init
  alias: Home Assistant Init
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: notify.mobile_app_galaxy_s10
    data_template:
      message: Home Assistant started!
- id: login_fail
  alias: Send notification upon failed login attempt
  trigger:
  - platform: state
    entity_id: persistent_notification.httplogin
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state != off }}'
  action:
  - service: notify.mobile_app_galaxy_s10
    data_template:
      title: Failed Home Assistant login attempt!
      message: 'IP: {{ states.persistent_notification.httplogin.attributes.message.split
        ("from ") [1]}}'
      data:
        url: http://www.ip-tracker.org/locator/ip-lookup.php?ip={{ states.persistent_notification.httplogin.attributes.message.split
          ("from ") [1]}}
- id: lg_tv_off
  alias: LG TV Off
  trigger:
  - entity_id: media_player.living_room_tv
    for: 0:05:00
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: media_player.lg_tv
    service: media_player.turn_off
- id: daily_backup
  alias: Weekly 3 AM Backup
  trigger:
    platform: time
    at: '3:00:00'
  action:
  - service: hassio.snapshot_full
    data_template:
      name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
  - delay: 07:00:00
  - service: hassio.addon_stdin
    data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
- id: hall_light_sunset
  alias: Hall light on at sunset
  trigger:
    event: sunset
    platform: sun
    offset: +00:00:00
  condition: []
  action:
    service: switch.turn_on
    entity_id: switch.my_smart_plug_mini
- id: hall_light_midnight
  alias: Hall light off at midnight
  trigger:
    platform: time
    at: 00:00:00
  condition: []
  action:
    service: switch.turn_off
    entity_id: switch.my_smart_plug_mini
