automation: !include automations.yaml
automation old: !include_dir_list automations

camera:
  - platform: generic
    name: Living Room
    still_image_url: !secret camera_1_url
  - platform: generic
    name: Porch
    still_image_url: !secret camera_2_url
  - platform: generic
    name: Puppies
    still_image_url: !secret camera_3_url
  - platform: generic
    name: Garage
    still_image_url: !secret camera_4_url

config:

cover: 
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain

discovery:

ecobee:
  api_key: !secret ecobee_api_key 

frontend:
                                                  
google_assistant:
  project_id: !secret google_assistant_project_id
  secure_devices_pin: !secret google_assistant_secure_devices_pin
  service_account: !include .google_service_account.json
  report_state: true
  exposed_domains:
    - cover
    - media_player
    - switch
    - light
    - script

group: !include groups.yaml

history:
  exclude: 
    domains:
    - updater
    - camera
    - script
    - sun
    - automation
    - zone
    - zwave
    - input_boolean

homeassistant:
  customize: !include customize.yaml
  elevation: !secret homeassistant_elevation
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  name: Home
  time_zone: !secret homeassistant_time_zone
  unit_system: imperial

input_boolean:
  cam_1_notify:
    name: Send notifications when cam 1 detects motion
    icon: mdi:cellphone-wireless
  cam_2_notify:
    name: Send notifications when cam 2 detects motion
    icon: mdi:cellphone-wireless
  cam_3_notify:
    name: Send notifications when cam 3 detects motion
    icon: mdi:cellphone-wireless
  cam_4_notify:
    name: Send notifications when cam 4 detects motion
    icon: mdi:cellphone-wireless    

logbook:

logger: 
  # Severities: critical, fatal, error, warning, warn, info, debug, notset
  default: error
  logs:
    homeassistant.core: warning
    # homeassistant.components.notify: debug
    homeassistant.components.automation: debug
    homeassistant.components.shell_command: debug

map:

mobile_app:

notify: 
  - platform: pushbullet
    name: Pushbullet
    api_key: !secret pushbullet_api_key  
  - platform: webostv
    host: 192.168.1.19
    name: lg_tv
    
panel_custom:
  - name: my-panel
    sidebar_title: TodoMVC
    sidebar_icon: mdi:work
    js_url: /local/my-panel.js
    config:
      who: world

panel_iframe:
  cams:
    title: Cams site
    icon: mdi:sunglasses
    url: !secret cams_url

recorder:
  purge_keep_days: 7
  db_url: !secret recorder_db_url
  exclude:
    entities:
      - media_player.galaxy_s7

sensor: !include sensors.yaml

script: !include scripts.yaml

shell_command: 
  cam_2_snapshot: "curl -X GET $(sh shell/secret.sh 'camera_2_url') > www/images/snapshot_cam_2.jpg"
  secret: /usr/share/hassio/homeassistant/shell/secret.sh
  set_pihole_hosts: /usr/share/hassio/homeassistant/shell/set_pihole_hosts.sh

sun:

# switch:
#   - platform: command_line
#     switches:
#       pihole_switch:
#         command_on: !secret pihole_command_on
#         command_off: !secret pihole_command_off
#         command_state: "curl -X GET 'http://192.168.1.2:4865/admin/api.php?status'"
#         value_template: "{{ value_json.status == 'enabled' }}"    
        
system_health:      

tplink: 

# tts:
#   - platform: google_translate
#     service_name: google_say

updater:
  include_used_components: true

webostv: 
  host: 192.168.1.19
  name: LG TV  