automation: !include automations.yaml
automation old: !include_dir_list automations

camera:
  - platform: generic
    name: Living Room
    still_image_url: !secret camera_1_url
  - platform: generic
    name: Porch
    still_image_url: !secret camera_2_url
  - platform: generic
    name: Puppies
    still_image_url: !secret camera_3_url
  - platform: generic
    name: Garage
    still_image_url: !secret camera_4_url

cloud:
  google_actions:
    filter:
      include_entities:
        - cover.garage_door
        - media_player.lg_tsw
        - script.notify_patrick
        - script.restart_home_assistant
    entity_config:
      media_player.lg_tv:
        name: LG TV
        room: living room

config:

cover: 
  platform: myq
  username: !secret myq_username
  password: !secret myq_password
  type: chamberlain

discovery:

ecobee:
  api_key: !secret ecobee_api_key 

frontend:

group: !include groups.yaml

history:
  exclude: 
    domains:
    - updater
    - camera
    - script
    - sun
    - automation
    - zone
    - zwave
    - input_boolean

http:
  api_password: !secret http_api_password 
  base_url: !secret http_base_url
  ip_ban_enabled: true
  login_attempts_threshold: 10
  trusted_proxies: !secret http_trusted_proxies
  use_x_forwarded_for: true

homeassistant:
  customize: !include customize.yaml
  elevation: !secret homeassistant_elevation
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  name: Home
  time_zone: !secret homeassistant_time_zone
  unit_system: imperial

logbook:

logger: 
  # Severities: critical, fatal, error, warning, warn, info, debug, notset
  default: error
  logs:
    homeassistant.core: warning
    homeassistant.components.notify: debug
    homeassistant.components.automation: debug

map:

media_player: 
  - platform: webostv
    name: LG TV
    host: 192.168.1.19

notify: 
  - platform: pushbullet
    name: Pushbullet
    api_key: !secret pushbullet_api_key  
  - platform: webostv
    host: 192.168.1.19
    name: lg_tv

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator_url
  cams:
    title: Cams
    icon: mdi:sunglasses
    url: !secret cams_url
  pihole:
    title: Pi-hole
    icon: mdi:block-helper
    url: !secret pihole_url  

recorder:
  purge_keep_days: 14
  db_url: !secret recorder_db_url
  exclude:
    entities:
      - media_player.galaxy_s7

sensor: !include sensors.yaml

script: !include scripts.yaml

shell_command: 
  secret: /usr/share/hassio/homeassistant/shell/secret.sh
  set_pihole_hosts: /usr/share/hassio/homeassistant/shell/set_pihole_hosts.sh

sun:

switch:
  - platform: tplink
    host: 192.168.1.64  

tts:
  - platform: google

updater:
  include_used_components: true
