automation: !include automations.yaml
automation old: !include_dir_list automations

camera:
  - platform: generic
    name: Porch
    still_image_url: !secret camera_1_url
  - platform: generic
    name: Living Room
    still_image_url: !secret camera_2_url
  - platform: generic
    name: Garage
    still_image_url: !secret camera_3_url
  - platform: generic
    name: Basement
    still_image_url: !secret camera_4_url

config:

discovery:

frontend:
                                                  
google_assistant:
  project_id: !secret google_assistant_project_id
  secure_devices_pin: !secret google_assistant_secure_devices_pin
  service_account: !include .google_service_account.json
  report_state: true
  exposed_domains:
    - cover
    - script
    - light
  entity_config:
    media_player.lg_tv:
      name: LG TV
      room: Living Room

group: !include groups.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5

history:
  exclude: 
    domains:
    - updater
    - camera
    - script
    - sun
    - automation
    - zone
    - input_boolean

homeassistant:
  customize: !include customize.yaml
  elevation: !secret homeassistant_elevation
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  name: Home
  time_zone: !secret homeassistant_time_zone
  unit_system: imperial

input_boolean:
  cam_1_notify:
    name: Send notifications when cam 1 detects motion
    icon: mdi:cellphone-nfc
  cam_2_notify:
    name: Send notifications when cam 2 detects motion
    icon: mdi:cellphone-nfc
  cam_3_notify:
    name: Send notifications when cam 3 detects motion
    icon: mdi:cellphone-nfc
  cam_4_notify:
    name: Send notifications when cam 4 detects motion
    icon: mdi:cellphone-nfc

logbook:

logger: 
  # Severities: critical, fatal, error, warning, warn, info, debug, notset
  default: error
  logs:
    homeassistant.core: warning
    # homeassistant.components.notify: debug
    #homeassistant.components.automation: debug
    #homeassistant.components.shell_command: debug
    homeassistant.components.http: warning

map:

mobile_app:

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id
  # subscriber_id: !secret nest_subscriber_id

  
notify: 
  - platform: pushbullet
    name: Pushbullet
    api_key: !secret pushbullet_api_key  
  #- platform: webostv
  #  host: 192.168.1.19
  #  name: lg_tv
  - name: weatherdata
    platform: file
    filename: weatherdata.csv  

recorder:
  purge_keep_days: 3
  db_url: !secret recorder_db_url
  exclude:
    domains:
      - input_boolean
      - input_number
      - input_select
      - input_text
      - sun
      - weather
      - camera  
    entities:
      - script.motion_detected_notifications
      - sensor.processor_use
      - sensor.memory_use_percent
      - sensor.ha_last_reboot
      - sensor.ha_uptime
      - sensor.processor_use_percent
    event_types:
      - call_service      
      
sensor: !include sensors.yaml

script: !include scripts.yaml

shell_command: 
  cam_2_snapshot: "curl -X GET $(sh shell/secret.sh 'camera_2_url') > www/images/snapshot_cam_2.jpg"
  secret: /usr/share/hassio/homeassistant/shell/secret.sh
  set_pihole_hosts: /usr/share/hassio/homeassistant/shell/set_pihole_hosts.sh
  snapshot_to_disk: /bin/bash -c "echo '{{ image_data }}' | base64 -d > www/images/snapshot_cam_{{ channel_number }}.jpg"

sun:

# switch:
#   - platform: command_line
#     switches:
#       pihole_switch:
#         command_on: !secret pihole_command_on
#         command_off: !secret pihole_command_off
#         command_state: "curl -X GET 'http://192.168.1.2:4865/admin/api.php?status'"
#         value_template: "{{ value_json.status == 'enabled' }}"    
        
system_health:    

timer:
  disable_cams:
    duration: '01:00:00'

tplink: 

# tts:
#   - platform: google_translate
#     service_name: google_say

updater:
  include_used_components: true

webostv:
  host: 192.168.1.25
  name: LG TV