automation: !include automations.yaml
automation old: !include_dir_list automations

cloud:

config:

cover: 
  platform: myq
  username: !secret myq_username
  password: !secret myq_password
  type: chamberlain

discovery:

ecobee:
  api_key: !secret ecobee_api_key 

frontend:

group: !include groups.yaml

history:

http:
  api_password: !secret http_api_password 
  base_url: !secret http_base_url
  ip_ban_enabled: true
  login_attempts_threshold: 10
  trusted_proxies: !secret http_trusted_proxies
  use_x_forwarded_for: true

homeassistant:
  # customize: !include customize.yaml
  elevation: !secret homeassistant_elevation
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  name: Home
  time_zone: !secret homeassistant_time_zone
  unit_system: imperial

logbook:

logger: 
  # Severities: critical, fatal, error, warning, warn, info, debug, notset
  default: error
  logs:
    homeassistant.core: warning
    homeassistant.components.notify: debug
    homeassistant.components.automation: debug

map:

notify: 
  - platform: pushbullet
    name: Pushbullet
    api_key: !secret pushbullet_api_key  

recorder:
  purge_keep_days: 14
  exclude:
    entities:
      - media_player.galaxy_s7

sensor:
  - platform: yr

script: !include scripts.yaml

sun:

tts:
  - platform: google

updater:
  include_used_components: true
